package basic_code;

import io.github.bonigarcia.wdm.WebDriverManager;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.edge.EdgeDriver;

public class XPath_Login {

	public static void main(String[] args) throws InterruptedException {
		WebDriverManager.edgedriver().setup();
		WebDriver driver = new EdgeDriver();
		driver.get("https://www.ptuexam.com/login"); // -> to hit the url
		driver.manage().window().maximize();
		System.out.println("set up completed by aman");

		// Syntax of XPath -> //tagName[@attribute='value']

		driver.findElement(By.xpath("//*[@id='username']")).sendKeys("1801972");
		// driver.findElement(By.xpath("//*[@value='']")).sendKeys("1801972"); // we
		// write xpath in many ways
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("k@mboj123");
		// driver.findElement(By.xpath("//*[@id=\"root\"]/main/div[2]/div/form/button/span[1]")).click();
		// // get this xpath from Chrome browser generated
		driver.findElement(By.xpath("//*[@class='MuiButton-label']")).click(); 
		// this XPath is generated by my-self
		// driver.findElement(By.className("MuiButton-label")).click();
		// click on sign in button using className locator, only used when no space
		// there
	}
}
